### ISSUE TITLE
Keeps outputting errors, causing the VSCode output window to open

### ISSUE THREAD

**Issue by frenck** [sourcery-ai/sourcery-vscode#1]
I was curious about this, so I installed it immediately.

It actually gives some nice suggestions now an then, but the VSCode extensions is mainly throwing errors in the output console:

```txt
Ignoring notification for unknown method $/setTraceNotification
Failed to handle request 87
Traceback (most recent call last):
  File "/home/frenck/.vscode-server/extensions/sourcery.sourcery-0.1.0/binaries/sourcery-0.5.15-linux/pyls_jsonrpc/endpoint.py", line 113, in consume
  File "/home/frenck/.vscode-server/extensions/sourcery.sourcery-0.1.0/binaries/sourcery-0.5.15-linux/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
  File "/home/frenck/.vscode-server/extensions/sourcery.sourcery-0.1.0/binaries/sourcery-0.5.15-linux/pyls_jsonrpc/dispatchers.py", line 23, in handler
  File "/home/frenck/.vscode-server/extensions/sourcery.sourcery-0.1.0/binaries/sourcery-0.5.15-linux/sourcery/lsp/sourcery_ls.py", line 521, in m_text_document__code_action
  File "/home/frenck/.vscode-server/extensions/sourcery.sourcery-0.1.0/binaries/sourcery-0.5.15-linux/sourcery/lsp/sourcery_ls.py", line 366, in code_actions
KeyError: 'code'
[Error - 3:24:52 PM] Request textDocument/codeAction failed.
  Message: KeyError: 'code'
  Code: -32602 
[object Object]
```

This causes VSCode to constantly throwing a warning popup in the bottom and the terminal constantly switches away to the output window to show me this.

It doesn't happen with specific files, but all files. Most of them were large Python file.

Disabled the extension at this point, as it makes working completely impossible.

**Comment by Hellebore** [comment]
Can see the problem. Will fix as soon as I can!

**Comment by Hellebore** [comment]
We've just updated to version 0.1.1 which should fix it. Please give it a try!

**Comment by frenck** [comment]
It works like a charm! Thanks for the quick fix! ❤️
