### ISSUE TITLE
Unable to install extension in dev container -  "PackageIsUnreadable"

### ISSUE THREAD

**Issue by bkcsfi** [sourcery-ai/sourcery-vscode#123]
I have been using sourcery-vscode with a devcontainer for months, but sometime in the past few weeks something changed and now I can no longer install it.

I'm running
```
Version: 1.76.0-insider
Commit: 25514d899f4bd877803defb213719f8af3d997d3
Date: 2023-02-07T05:25:12.243Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.4.0-125-generic
Sandboxed: Yes
```
I have setup a devcontainer with python 3.11 on a remote host (accessed via ssh)

When I open the extensions view, enter 'sourcery', it says 
```
This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in 'Dev Container:
```
When I click `install in dev container: python3.11 @ ssh: ...`  the install eventually fails

The remote server log shows the following

```
2023-02-08 16:36:38.155 [info] Getting Manifest... sourcery.sourcery
2023-02-08 16:36:43.913 [info] Installing extension: sourcery.sourcery
2023-02-08 16:36:44.070 [error] Error while installing the extension: sourcery.sourcery
2023-02-08 16:36:44.071 [error] Failed to install extension. sourcery.sourcery
2023-02-08 16:36:44.071 [error] Signature: PackageIsUnreadable
    at Pn.download (/vscode/vscode-server-insiders/bin/linux-x64/25514d899f4bd877803defb213719f8af3d997d3-insider/out/vs/server/node/server.main.js:113:1922)
    at async te.h (/vscode/vscode-server-insiders/bin/linux-x64/25514d899f4bd877803defb213719f8af3d997d3-insider/out/vs/server/node/server.main.js:149:92612)
2023-02-08 16:36:44.914 [error] Signature: PackageIsUnreadable
    at Pn.download (/vscode/vscode-server-insiders/bin/linux-x64/25514d899f4bd877803defb213719f8af3d997d3-insider/out/vs/server/node/server.main.js:113:1922)
    at async te.h (/vscode/vscode-server-insiders/bin/linux-x64/25514d899f4bd877803defb213719f8af3d997d3-insider/out/vs/server/node/server.main.js:149:92612)
```

**Comment by Hellebore** [comment]
Thanks for raising - does this still happen with the stable build of vscode rather than the insider one?

**Comment by bkcsfi** [comment]
Thank you for following up.

I have also tried the extension with non-insiders  build

```
Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:29:17.766Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.4.0-125-generic
Sandboxed: No
```

The sourcery extension does install in the non-insiders build. However there are some interesting differences between the two systems.

non-insiders, viewing un-installed extension:
![image](https://user-images.githubusercontent.com/6412502/217856833-25c76b13-e209-4541-9720-e5fe203c4334.png)

vs insiders build, viewing un-installed extension:

![image](https://user-images.githubusercontent.com/6412502/217857019-ee55c6be-2ee9-414f-a051-6981cc0417d6.png)

(they look the same). I'll now click 'install in dev container' 


non-insiders

![image](https://user-images.githubusercontent.com/6412502/217857392-cdcdb910-d9b9-4855-9daf-557f70b101c8.png)


but the insiders build wants to run the extension in the remote extension host

![image](https://user-images.githubusercontent.com/6412502/217857216-51cf5e14-100b-4ba8-be92-f80709e86d7f.png)

The instructions on the insiders build says "Please install the extension in 'Dev Container: Python 3.11 @ ssh://bob4' to enable" 

Is that not the same as "extension enabled on 'Dev container'" .. ?? In vs on?

Anyway, I suspect the insiders build may be interpreting the extension manifest differently than the non-insiders build (or whatever it uses to determine where the extension should be installed).

The setup for both insiders and non-insiders is the same:

- ssh to a remote host (use the remote explorer / choose 'remote', then ssh'
- open a folder on the remote host that contains a .devcontainer
- re-open the folder in the .devcontainer

In this case I'm using the stock Python 3.11 microsoft dev container

**Comment by bkcsfi** [comment]
reporting that with v1.0.5 and updated code-insiders, the extension now DOES install into the remote container

```
Version: 1.76.0-insider
Commit: f718f1ace394dba4255774ac3f1c9321f629f8ff
Date: 2023-02-13T05:29:38.257Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.4.0-125-generic
Sandboxed: Yes
```


First install attempt was just clicking install, which failed despite the 'Shared' output log  claiming the extension was installed

```
2023-02-13 11:43:05.068 [info] Getting Manifest... sourcery.sourcery
2023-02-13 11:43:05.087 [info] Installing extension: sourcery.sourcery
2023-02-13 11:43:09.875 [info] Extension signature verification: sourcery.sourcery. Verification status: Verified.
2023-02-13 11:43:09.925 [info] Removed the extension from uninstalled list: sourcery.sourcery
2023-02-13 11:43:10.118 [info] Extension installed successfully: sourcery.sourcery
```

its shown as disabled, same error as previously reported

![image](https://user-images.githubusercontent.com/6412502/218519744-6d85c611-e18c-462d-ab04-e20cda9a6973.png)

I then clicked 'install in dev container' and this time, it did install w/o error

remove server log:
```
023-02-13 16:48:29.864 [info] Getting Manifest... sourcery.sourcery
2023-02-13 16:48:35.529 [info] Installing extension: sourcery.sourcery
2023-02-13 16:49:11.311 [info] Extension signature verification: sourcery.sourcery. Verification status: Verified.
2023-02-13 16:49:16.075 [info] Extracted extension to /home/vscode/.vscode-server-insiders/extensions/.a1d33236-c6bb-434f-9622-697add1aeda4: sourcery.sourcery
2023-02-13 16:49:16.082 [info] Renamed to /home/vscode/.vscode-server-insiders/extensions/sourcery.sourcery-1.0.5
2023-02-13 16:49:16.084 [info] Extracting extension completed. sourcery.sourcery
2023-02-13 16:49:16.093 [info] Extension installed successfully: sourcery.sourcery
```

![image](https://user-images.githubusercontent.com/6412502/218520586-44c08691-72f2-4e74-9013-76f5d3ac0225.png)


closing this issue, thanks for getting v1.0.5 out the door.
