### ISSUE TITLE
Unable to upgrade/install extension

### ISSUE THREAD

**Issue by bpepple** [sourcery-ai/sourcery-vscode#43]
Got an error when attempting to update to v0.9.5, so uninstalled the currently installed version and attempted to do a install again. Failed with the following output error:

```
[2021-09-28 00:14:21.384] [renderer1] [error] ["validating: Corrupt ZIP: end of central directory record signature not found","    at F.downloadInstallableExtension (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)","    at async F.doRun (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)"]
[2021-09-28 00:14:21.401] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at F.downloadInstallableExtension (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)
    at async F.doRun (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)
[2021-09-28 00:15:11.253] [renderer1] [error] ["validating: Corrupt ZIP: end of central directory record signature not found","    at F.downloadInstallableExtension (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)","    at async F.doRun (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)"]
[2021-09-28 00:15:11.265] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at F.downloadInstallableExtension (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)
    at async F.doRun (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)
```

**Comment by Hellebore** [comment]
Thanks for raising - which OS and VS Code version are you on?

**Comment by bpepple** [comment]
> Thanks for raising - which OS and VS Code version are you on?

Fedora 34. VS Code-1.60.2

**Comment by Hellebore** [comment]
This may take a little while to investigate. For the moment you should be able to install the old version from here:
https://marketplace.visualstudio.com/items?itemName=sourcery.sourcery

**Comment by Hellebore** [comment]
@bpepple would you be able to try again with our latest version. 0.9.8?

**Comment by bpepple** [comment]
@Hellebore I got v0.9.8 installed, so this bug can probably be closed.  Thanks!
