### ISSUE TITLE
Error while installing 'Sourcery' extension.

### ISSUE THREAD

**Issue by Murithijoshua** [sourcery-ai/sourcery-vscode#76]
* I am using Ubuntu 20.04, with vs-code as my editor, past a week I was using Sourcery well until
it started misbehaving.
* I went ahead to uninstall the extension however I was Unable to reinstall it again
### NB:the logs are for Code-insider but are same with vs-code. I went ahead to counter check
**logs**
``` js
[2022-05-25 18:14:58.173] [renderer1] [warning] Via 'product.json#extensionEnabledApiProposals' extension 'visualstudioexptteam.vscodeintellicode-completions' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[2022-05-25 18:14:58.200] [renderer1] [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[2022-05-25 18:14:58.201] [renderer1] [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-nightly' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[2022-05-25 18:15:39.558] [renderer1] [error] ENOENT: no such file or directory, open '/home/joshua/.config/Code - Insiders/User/globalStorage/vscodevim.vim/.registers': Error: ENOENT: no such file or directory, open '/home/joshua/.config/Code - Insiders/User/globalStorage/vscodevim.vim/.registers'
[2022-05-25 18:16:42.126] [renderer1] [warning] Via 'product.json#extensionEnabledApiProposals' extension 'visualstudioexptteam.vscodeintellicode-completions' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[2022-05-25 18:16:42.155] [renderer1] [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[2022-05-25 18:16:42.156] [renderer1] [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-nightly' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[2022-05-25 18:16:43.287] [renderer1] [info] [eamodio.gitlens]: `git.commit` is not a valid menu identifier
[2022-05-25 18:16:45.393] [renderer1] [error] ENOENT: no such file or directory, open '/home/joshua/.config/Code - Insiders/User/globalStorage/vscodevim.vim/.registers': Error: ENOENT: no such file or directory, open '/home/joshua/.config/Code - Insiders/User/globalStorage/vscodevim.vim/.registers'
[2022-05-25 18:17:33.516] [renderer1] [error] Error: Unable to read file '/home/joshua/P.P/Community-Platform/data/db/journal/prealloc.1' (Unknown (FileSystemError): An unknown error occurred. Please consult the log for more details.)
    at Object.error (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:597:20314)
    at Object.onError (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:30057)
    at vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:29152
    at vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:27333
    at Array.forEach (<anonymous>)
    at y.emitError (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:27322)
    at y.error (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:26983)
    at vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:593:29980
    at m.invoke (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.deliver (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at j (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:3415)
    at D.onResponse (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4389)
    at D.onBuffer (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:4229)
    at vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:1817
    at m.invoke (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.deliver (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at EventEmitter.j (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:65:51277)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:881)
[2022-05-25 18:18:20.098] [renderer1] [error] RequestService#request (browser) - error https://sarrus.gallerycdn.vsassets.io/extensions/sarrus/sourcepawn-vscode/3.3.12/1653320310149/Microsoft.VisualStudio.Code.Manifest {}
[2022-05-25 18:18:20.708] [renderer1] [error] RequestService#request (browser) - error https://sarrus.gallery.vsassets.io/_apis/public/gallery/publisher/Sarrus/extension/sourcepawn-vscode/3.3.12/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
[2022-05-25 18:18:20.734] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.b.onerror (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:27645)
[2022-05-25 18:18:20.745] [renderer1] [error] ["Download: XHR failed","    at q.downloadInstallableExtension (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218780)","    at async q.doRun (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217398)"]
[2022-05-25 18:18:20.788] [renderer1] [error] XHR failed: Download: XHR failed
    at q.downloadInstallableExtension (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218780)
    at async q.doRun (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217398)
[2022-05-25 18:18:43.073] [renderer1] [info] Setting search error: Unexpected end of JSON input
[2022-05-25 18:18:43.093] [renderer1] [info] Setting search error: Unexpected end of JSON input
[2022-05-25 18:22:34.704] [renderer1] [error] ["Download: XHR failed","    at q.downloadInstallableExtension (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218780)","    at async q.doRun (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217398)"]
[2022-05-25 18:22:34.755] [renderer1] [error] XHR failed: Download: XHR failed
    at q.downloadInstallableExtension (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218780)
    at async q.doRun (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217398)
[2022-05-25 18:24:12.589] [renderer1] [warning] Shell integration failed to add capabilities within 10 seconds
[2022-05-25 18:25:44.224] [renderer1] [error] ["Download: XHR failed","    at q.downloadInstallableExtension (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218780)","    at async q.doRun (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217398)"]
[2022-05-25 18:25:44.261] [renderer1] [error] XHR failed: Download: XHR failed
    at q.downloadInstallableExtension (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218780)
    at async q.doRun (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217398)
[2022-05-25 18:31:01.535] [renderer1] [error] ["Download: XHR failed","    at q.downloadInstallableExtension (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218780)","    at async q.doRun (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217398)"]
[2022-05-25 18:31:01.576] [renderer1] [error] XHR failed: Download: XHR failed
    at q.downloadInstallableExtension (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218780)
    at async q.doRun (vscode-file://vscode-app/snap/code-insiders/1010/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217398)
[2022-05-25 18:31:53.416] [renderer1] [error] Cannot read properties of undefined (reading 'document'): TypeError: Cannot read properties of undefined (reading 'document')
    at /home/joshua/.vscode-insiders/extensions/vscodevim.vim-1.22.2/extensionBase.ts:239:40
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


```

**Comment by reka** [comment]
Hi @Murithijoshua ,

That's interesting, thanks a lot for reporting it. :+1: 
I have two questions.

1)
What was your use case when you got these errors?
Were you trying to install just the Sourcery extension? Or some other extensions as well?

E.g. the line about the error at 18:16:45 is referring to the vim extension `/home/joshua/.config/Code - Insiders/User/globalStorage/vscodevim.vim/.registers`

2)
You mentioned that Sourcery started misbehaving.
I'm curious how Sourcery misbehaved. What kind of errors did you experience?

Cheers,
Reka

**Comment by Murithijoshua** [comment]
Hi @reka 
1.(a)To first question, By default I have set an auto-update setting to all my extensions. with this in mind Sourcery was to update together with other extensions. In this case all extensions updated apart from sourcery.This execrated causing sourcery not to work as used.I went ahead uninstall it and reinstall which caused the error above. 
1(b). I was trying to install only Sourcery for vim its working perfectly well.

2. Started with:
* Unable to update sourcery
* Then pop up windows, The extension closed unexpectedly
* To try and cub this I went ahead to uninstall the same and got above error
* Tried installing with vsix I which worked but will not be able to update
![Screenshot from 2022-05-26 20-57-17](https://user-images.githubusercontent.com/37470288/170547548-d9dc3d44-1935-49cc-ac88-da02fecbeec7.png)

**Comment by reka** [comment]
Thanks a lot for sharing more info.

We looked into the issue and have multiple possible ideas what might be going on.

1.
It's strange that the logs contain several errors, but they don't mention "sourcery" at all.
=> This might indicate that the VSCode Insiders extension updater had some temporary issue.

2. The Sourcery extension is relatively big compared to other VSCode extensions. That can be a reason why the updater managed to update the other extensions, but not Sourcery. Especially when your internet connection was slow that time.

Let us know if you still experience issues with using or updating Sourcery.

**Comment by Murithijoshua** [comment]
Thanks, I will also go on and recheck about the same. Maybe install in a new Vscode enviroment.
