### ISSUE TITLE
 Error on startup in Windows 11

### ISSUE THREAD

**Issue by FeeeeK** [sourcery-ai/sourcery-vscode#87]
```
Traceback (most recent call last):
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\__main__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\binary\command_line_interface.py", line 25, in <module binary.command_line_interface>        
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\file_ast.py", line 11, in <module sourcery.code.file_ast>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\source_parser.py", line 41, in <module sourcery.code.source_parser>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\tree_sitter\parser.py", line 90, in <module sourcery.code.tree_sitter.parser>  
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\tree_sitter\parser.py", line 56, in parse_source_to_ast
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\tree_sitter\parser.py", line 67, in parse_source
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\tree_sitter\parser.py", line 75, in make_parser
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\tree_sitter\parser.py", line 84, in get_language
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\tree_sitter\parser.py", line 67, in parse_source
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\tree_sitter\parser.py", line 75, in make_parser
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\sourcery\code\tree_sitter\parser.py", line 84, in get_language
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\tree_sitter\__init__.py", line 82, in __init__  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\ctypes\__init__.py", line 452, in LoadLibrary
  File "D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'D:\vscode\data\extensions\sourcery.sourcery-0.12.1\sourcery_binaries\install\win\languages.so' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by reka** [comment]
Hi @FeeeeK ,

Thanks a lot for reporting this issue. :+1: That looks really strange, we'll investigate it.

Can you perhaps give us some more info about the context? That would be super helpful for the troubleshooting.

1. Have you just installed Sourcery when you got this error? Or were you trying to upgrade to version 0.12.1 ?
2. Which Windows version are you using?

Thanks a lot in advance.

**Comment by reka** [comment]
Hi @FeeeeK ,

We're investigating this issue.
Can you perhaps give us a bit more info about your environment?

1. Which Windows version are you using?
2. Which package manager are you using? PyPI, conda, sth completely different?

**Comment by FeeeeK** [comment]
1. Windows 11
2. PyPI

**Comment by FeeeeK** [comment]
This bug appears only in 0.12.1
![image](https://user-images.githubusercontent.com/26704473/176551156-3e0b84a8-81c5-48b8-9291-92704d36eda2.png)

**Comment by nezinomas** [comment]
I am getting the same error on Windows 11, Phyton 3.92, Sourcery v0.12.3

[Info  - 22:04:38] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\__main__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\binary\command_line_interface.py", line 25, in <module binary.command_line_interface>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\sourcery\code\file_ast.py", line 11, in <module sourcery.code.file_ast>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\sourcery\code\source_parser.py", line 41, in <module sourcery.code.source_parser>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\sourcery\code\tree_sitter\parser.py", line 90, in <module sourcery.code.tree_sitter.parser>
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\sourcery\code\tree_sitter\parser.py", line 56, in parse_source_to_ast
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\sourcery\code\tree_sitter\parser.py", line 67, in parse_source
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\sourcery\code\tree_sitter\parser.py", line 75, in make_parser
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\sourcery\code\tree_sitter\parser.py", line 84, in get_language
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\tree_sitter\__init__.py", line 82, in __init__
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\ctypes\__init__.py", line 452, in LoadLibrary
  File "c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'c:\Users\Usr\VSCODE~1\EXTENS~1\SOURCE~1.3\SOURCE~1\install\win\languages.so' (or one of its dependencies). Try using the full path with constructor syntax.
[Error - 22:04:41] Connection to server got closed. Server will not be restarted.

**Comment by FeeeeK** [comment]
@nezinomas Try to install version 0.12.1 it worked for me

**Comment by FeeeeK** [comment]
It seems that last versions work as intended, so there is no need to keep this issue open
